version: "3"
services:
  rpc:
    image: jfinchain/erigon
    user: root
    entrypoint: /root/init-script.sh
    command:
      - "--datadir=/datadir/erigon"
      - "--bootnodes=enode://7f2060647bb6b3598cde7c409fc433a1d5f4051b4887fdbf50cccc0fd66c66b1ed5479d8e74afe81451dfb58a82a47b36b6b144e636b548224d58029417bef21@65.108.14.187:30303,enode://d1438b13c5e2d7299a648cbbc720025376b997a4af277633d96724d4273c54ca739290efc13e2c4454518d5d048839075575e4e49d554984a802acf7c949196e@65.108.0.235:30303"
      - "--networkid=3501"
      - "--http"
      - "--http.addr=0.0.0.0"
      - "--http.api=eth,engine,erigon,web3,net,debug,trace,txpool,ots"
      - "--http.port=8545"
      - "--http.corsdomain=*"
      - "--http.vhosts=*"
      - "--ws"
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
    volumes:
      - "./genesis.json:/datadir/genesis.json"
      - "./datadir/erigon:/datadir/erigon"
      - "./init-script.sh:/root/init-script.sh"
    restart: always

