version: "3"
services:

  node:
    image: domecloud/jfin-node-testnet
    command:
      - "geth"
      - "--datadir=/datadir"
      - "--genesis=/datadir/genesis.json"
      - "--networkid=3503"
      - "--mine"
      - "--miner.gasprice=20000000000"
      - "--password=/datadir/password.txt"
      - "--allow-insecure-unlock"
      - "--unlock=0x00a601f45688dba8a070722073b015277cf36725"
      - "--miner.etherbase=0x00a601f45688dba8a070722073b015277cf36725"
      - "--nodekeyhex=51c55f06f286aadfcdaddf15846ad1020ad9c1ba8a08b0e8764830b3a7cf6cb0"
      - "--miner.gasprice=20000000000"
      - "--http"
      - "--http.addr=0.0.0.0"
      - "--http.api=eth,net,web3,debug,txpool"
      - "--http.port=8545"
      - "--http.corsdomain=*"
      - "--http.vhosts=*"
      - "--ws"
      - "--ws.addr=0.0.0.0"
      - "--ws.api=eth,net,web3,debug,txpool"
      - "--ws.port=8546"
      - "--ws.origins=*"
      - "--syncmode=full"
      - "--gcmode=archive"
      - "--rpc.allow-unprotected-txs"
    ports:
      - "8005:8545"
      - "8006:8546"
    volumes:
      - "./genesis.json:/datadir/genesis.json"
      - "./keystore:/datadir/keystore"
      - "./password.txt:/datadir/password.txt"
      - "./datadir/validator_1:/datadir/geth"
    restart: always

  db:
    image: postgres:13.6
    restart: always
    #container_name: 'tch-postgres'
    environment:
        POSTGRES_PASSWORD: ''
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - ./datadir/postgres-data:/var/lib/postgresql/data

  blockscout:
    depends_on:
      - db
    image: domecloud/blockscout-jfin-testnet
    restart: always
    #container_name: 'tch-blockscout'
    links:
      - db:database
    command: 'mix do ecto.create, ecto.migrate, phx.server'
    env_file:
      -  ./envs/common-blockscout.env
    environment:
        ETHEREUM_JSONRPC_VARIANT: 'geth'
        BLOCK_TRANSFORMER: 'base'
        ETHEREUM_JSONRPC_HTTP_URL: http://65.108.44.103:8005/
        DATABASE_URL: postgresql://postgres:@db:5432/blockscout?ssl=false
        ECTO_USE_SSL: 1
    ports:
      - 4001:4000

